cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'

brew 'wget'
brew 'zsh'
brew 'bash'
brew 'mas'
brew 'curl'
brew 'git'
brew 'lua'
brew 'vim', args: ['with-lua']
brew 'screenfetch'
brew 'mysql'
brew 'openssl'
brew 'w3m'
brew 'ctags'
brew 'pyenv'
brew 'flake8'
brew 'gcc'
brew 'perl'
brew 'ruby'
brew 'go'
brew 'node'
brew 'coffeescript'
brew 'jsonlint'
brew 'write-good'

cask 'karabiner-elements'
cask 'mplayerx'
cask 'java'

mas 'LINE', id: 539883307
mas 'The Unarchiver', id: 425424353
