tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'

brew 'curl'
brew 'git'
brew 'irssi'
brew 'mono'
brew 'mysql'
brew 'python'
brew 'screenfetch'
brew 'vim'
brew 'perl'
brew 'ruby'
brew 'wget'
brew 'zsh'
brew 'mas'
brew 'maven'

cask 'google-chrome'
cask 'google-japanese-ime'
cask 'iterm2'
cask 'firefox'
cask 'skype'
cask 'torbrowser'
cask 'mplayerx'
cask 'virtualbox'

mas 'Twitter', id: 409789998
mas 'LINE', id: 539883307